name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build for Linux AMD64
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w -X main.version=${{ steps.get_version.outputs.VERSION }}" \
            -o blugo-linux-amd64 ./cmd/blugo
          tar czf blugo-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz blugo-linux-amd64
          sha256sum blugo-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz > blugo-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz.sha256

      - name: Build for Linux ARM64
        env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w -X main.version=${{ steps.get_version.outputs.VERSION }}" \
            -o blugo-linux-arm64 ./cmd/blugo
          tar czf blugo-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz blugo-linux-arm64
          sha256sum blugo-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz > blugo-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            blugo-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz
            blugo-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz.sha256
            blugo-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz
            blugo-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
